[package]
name = "ferriscompany"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ferriscompany_server"
path = "src/bin/server/main.rs"

[lib]
name = "ferriscompany"
path = "src/lib/lib.rs"

[dependencies]
neo4rs = "0.8.0"
thiserror = "1.0.64"
uuid = { version = "1.10.0", features = ["v4"] }
